// Server-only copy for the Discord reviews flow (IT default, EN available).

export type Locale = "it" | "en";

export const REVIEW_COPY = {
  it: {
    panelTitle: "⭐ Recensioni Aron Mod",
    panelDescription: [
      "Hai provato Aron Mod? Raccontaci la tua esperienza.",
      "",
      "Le recensioni vengono pubblicate in forma **anonima** dopo l'approvazione dello staff.",
    ].join("\n"),
    panelButton: "📝 Lascia una recensione",
    modalTitle: "Lascia una recensione",
    modalRating: "Voto da 1 a 5",
    modalRatingPlaceholder: "Es. 5",
    modalBody: "La tua recensione",
    modalBodyPlaceholder: "Racconta la tua esperienza (minimo 20 caratteri)",
    submitted: "✅ Grazie! La tua recensione è stata inviata ed è in attesa di approvazione.",
    invalidRating: "⚠️ Il voto deve essere un numero intero da 1 a 5.",
    invalidBody: "⚠️ La recensione deve contenere tra 20 e 1000 caratteri.",
    alreadyPending: "⚠️ Hai già una recensione in attesa di approvazione.",
    alreadyApproved: "⚠️ Hai già una recensione pubblicata.",
    rateLimited: "⚠️ Troppi tentativi. Riprova tra qualche minuto.",
    notConfigured: "⚠️ Il sistema recensioni non è configurato. Avvisa lo staff.",
    wrongChannel: "⚠️ Questo comando può essere usato solo nel canale recensioni.",
    noReviewers: "⚠️ Nessun reviewer è configurato. Avvisa lo staff.",
    genericError: "⚠️ Errore temporaneo. Riprova più tardi.",
    staffOnly: "⛔ Solo lo staff può usare questo comando.",
    reviewerOnly: "⛔ Solo un reviewer autorizzato può gestire questa recensione.",
    panelPublished: "✅ Pannello recensioni pubblicato nel canale.",
    approved: "✅ Recensione approvata e pubblicata.",
    rejected: "❌ Recensione rifiutata. Nulla è stato pubblicato.",
    alreadyHandled: "⚠️ Questa recensione è già stata gestita.",
    notFound: "⚠️ Recensione non trovata.",
    publicAnonymous: "Recensione anonima",
    publicApproved: "Approvata dallo staff",
    dmApproved: "✅ La tua recensione è stata approvata e pubblicata in forma anonima. Grazie!",
    dmRejected: "❌ La tua recensione non è stata approvata. Puoi inviarne una nuova.",
  },
  en: {
    panelTitle: "⭐ Aron Mod Reviews",
    panelDescription: [
      "Tried Aron Mod? Tell us about your experience.",
      "",
      "Reviews are published **anonymously** after staff approval.",
    ].join("\n"),
    panelButton: "📝 Leave a review",
    modalTitle: "Leave a review",
    modalRating: "Rating from 1 to 5",
    modalRatingPlaceholder: "e.g. 5",
    modalBody: "Your review",
    modalBodyPlaceholder: "Tell us about your experience (min 20 characters)",
    submitted: "✅ Thanks! Your review was submitted and is waiting for approval.",
    invalidRating: "⚠️ The rating must be a whole number from 1 to 5.",
    invalidBody: "⚠️ The review must be between 20 and 1000 characters.",
    alreadyPending: "⚠️ You already have a review waiting for approval.",
    alreadyApproved: "⚠️ You already have a published review.",
    rateLimited: "⚠️ Too many attempts. Try again in a few minutes.",
    notConfigured: "⚠️ The review system is not configured. Please tell the staff.",
    wrongChannel: "⚠️ This command can only be used in the reviews channel.",
    noReviewers: "⚠️ No reviewer is configured. Please tell the staff.",
    genericError: "⚠️ Temporary error. Please try again later.",
    staffOnly: "⛔ Only staff can use this command.",
    reviewerOnly: "⛔ Only an authorized reviewer can manage this review.",
    panelPublished: "✅ Review panel published in the channel.",
    approved: "✅ Review approved and published.",
    rejected: "❌ Review rejected. Nothing was published.",
    alreadyHandled: "⚠️ This review has already been handled.",
    notFound: "⚠️ Review not found.",
    publicAnonymous: "Anonymous review",
    publicApproved: "Approved by staff",
    dmApproved: "✅ Your review was approved and published anonymously. Thank you!",
    dmRejected: "❌ Your review was not approved. You can submit a new one.",
  },
} as const;

export function rc(locale: Locale) {
  return REVIEW_COPY[locale === "en" ? "en" : "it"];
}
