/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcquistoCompletatoRouteImport } from './routes/acquisto-completato'
import { Route as CheckoutTokenRouteImport } from './routes/checkout.$token'
import { Route as ApiPublicDiscordAdminSetupRouteImport } from './routes/api/public/discord-admin-setup'
import { Route as ApiPublicDiscordInteractionsRouteImport } from './routes/api/public/discord-interactions'
import { Route as ApiPublicDiscordOauthCallbackRouteImport } from './routes/api/public/discord-oauth-callback'
import { Route as ApiPublicDiscordOauthStartRouteImport } from './routes/api/public/discord-oauth-start'
import { Route as ApiPublicDiscordRegisterCommandsRouteImport } from './routes/api/public/discord-register-commands'
import { Route as ApiPublicLicenseValidateRouteImport } from './routes/api/public/license-validate'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquistoCompletatoRoute = AcquistoCompletatoRouteImport.update({
  id: '/acquisto-completato',
  path: '/acquisto-completato',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTokenRoute = CheckoutTokenRouteImport.update({
  id: '/checkout/$token',
  path: '/checkout/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordAdminSetupRoute =
  ApiPublicDiscordAdminSetupRouteImport.update({
    id: '/api/public/discord-admin-setup',
    path: '/api/public/discord-admin-setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordInteractionsRoute =
  ApiPublicDiscordInteractionsRouteImport.update({
    id: '/api/public/discord-interactions',
    path: '/api/public/discord-interactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordOauthCallbackRoute =
  ApiPublicDiscordOauthCallbackRouteImport.update({
    id: '/api/public/discord-oauth-callback',
    path: '/api/public/discord-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordOauthStartRoute =
  ApiPublicDiscordOauthStartRouteImport.update({
    id: '/api/public/discord-oauth-start',
    path: '/api/public/discord-oauth-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordRegisterCommandsRoute =
  ApiPublicDiscordRegisterCommandsRouteImport.update({
    id: '/api/public/discord-register-commands',
    path: '/api/public/discord-register-commands',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseValidateRoute =
  ApiPublicLicenseValidateRouteImport.update({
    id: '/api/public/license-validate',
    path: '/api/public/license-validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal-webhook',
  path: '/api/public/paypal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisto-completato': typeof AcquistoCompletatoRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/api/public/discord-admin-setup': typeof ApiPublicDiscordAdminSetupRoute
  '/api/public/discord-interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord-oauth-callback': typeof ApiPublicDiscordOauthCallbackRoute
  '/api/public/discord-oauth-start': typeof ApiPublicDiscordOauthStartRoute
  '/api/public/discord-register-commands': typeof ApiPublicDiscordRegisterCommandsRoute
  '/api/public/license-validate': typeof ApiPublicLicenseValidateRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisto-completato': typeof AcquistoCompletatoRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/api/public/discord-admin-setup': typeof ApiPublicDiscordAdminSetupRoute
  '/api/public/discord-interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord-oauth-callback': typeof ApiPublicDiscordOauthCallbackRoute
  '/api/public/discord-oauth-start': typeof ApiPublicDiscordOauthStartRoute
  '/api/public/discord-register-commands': typeof ApiPublicDiscordRegisterCommandsRoute
  '/api/public/license-validate': typeof ApiPublicLicenseValidateRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisto-completato': typeof AcquistoCompletatoRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/api/public/discord-admin-setup': typeof ApiPublicDiscordAdminSetupRoute
  '/api/public/discord-interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord-oauth-callback': typeof ApiPublicDiscordOauthCallbackRoute
  '/api/public/discord-oauth-start': typeof ApiPublicDiscordOauthStartRoute
  '/api/public/discord-register-commands': typeof ApiPublicDiscordRegisterCommandsRoute
  '/api/public/license-validate': typeof ApiPublicLicenseValidateRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisto-completato'
    | '/checkout/$token'
    | '/api/public/discord-admin-setup'
    | '/api/public/discord-interactions'
    | '/api/public/discord-oauth-callback'
    | '/api/public/discord-oauth-start'
    | '/api/public/discord-register-commands'
    | '/api/public/license-validate'
    | '/api/public/paypal-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisto-completato'
    | '/checkout/$token'
    | '/api/public/discord-admin-setup'
    | '/api/public/discord-interactions'
    | '/api/public/discord-oauth-callback'
    | '/api/public/discord-oauth-start'
    | '/api/public/discord-register-commands'
    | '/api/public/license-validate'
    | '/api/public/paypal-webhook'
  id:
    | '__root__'
    | '/'
    | '/acquisto-completato'
    | '/checkout/$token'
    | '/api/public/discord-admin-setup'
    | '/api/public/discord-interactions'
    | '/api/public/discord-oauth-callback'
    | '/api/public/discord-oauth-start'
    | '/api/public/discord-register-commands'
    | '/api/public/license-validate'
    | '/api/public/paypal-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquistoCompletatoRoute: typeof AcquistoCompletatoRoute
  CheckoutTokenRoute: typeof CheckoutTokenRoute
  ApiPublicDiscordAdminSetupRoute: typeof ApiPublicDiscordAdminSetupRoute
  ApiPublicDiscordInteractionsRoute: typeof ApiPublicDiscordInteractionsRoute
  ApiPublicDiscordOauthCallbackRoute: typeof ApiPublicDiscordOauthCallbackRoute
  ApiPublicDiscordOauthStartRoute: typeof ApiPublicDiscordOauthStartRoute
  ApiPublicDiscordRegisterCommandsRoute: typeof ApiPublicDiscordRegisterCommandsRoute
  ApiPublicLicenseValidateRoute: typeof ApiPublicLicenseValidateRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisto-completato': {
      id: '/acquisto-completato'
      path: '/acquisto-completato'
      fullPath: '/acquisto-completato'
      preLoaderRoute: typeof AcquistoCompletatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$token': {
      id: '/checkout/$token'
      path: '/checkout/$token'
      fullPath: '/checkout/$token'
      preLoaderRoute: typeof CheckoutTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord-admin-setup': {
      id: '/api/public/discord-admin-setup'
      path: '/api/public/discord-admin-setup'
      fullPath: '/api/public/discord-admin-setup'
      preLoaderRoute: typeof ApiPublicDiscordAdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord-interactions': {
      id: '/api/public/discord-interactions'
      path: '/api/public/discord-interactions'
      fullPath: '/api/public/discord-interactions'
      preLoaderRoute: typeof ApiPublicDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord-oauth-callback': {
      id: '/api/public/discord-oauth-callback'
      path: '/api/public/discord-oauth-callback'
      fullPath: '/api/public/discord-oauth-callback'
      preLoaderRoute: typeof ApiPublicDiscordOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord-oauth-start': {
      id: '/api/public/discord-oauth-start'
      path: '/api/public/discord-oauth-start'
      fullPath: '/api/public/discord-oauth-start'
      preLoaderRoute: typeof ApiPublicDiscordOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord-register-commands': {
      id: '/api/public/discord-register-commands'
      path: '/api/public/discord-register-commands'
      fullPath: '/api/public/discord-register-commands'
      preLoaderRoute: typeof ApiPublicDiscordRegisterCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license-validate': {
      id: '/api/public/license-validate'
      path: '/api/public/license-validate'
      fullPath: '/api/public/license-validate'
      preLoaderRoute: typeof ApiPublicLicenseValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal-webhook': {
      id: '/api/public/paypal-webhook'
      path: '/api/public/paypal-webhook'
      fullPath: '/api/public/paypal-webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquistoCompletatoRoute: AcquistoCompletatoRoute,
  CheckoutTokenRoute: CheckoutTokenRoute,
  ApiPublicDiscordAdminSetupRoute: ApiPublicDiscordAdminSetupRoute,
  ApiPublicDiscordInteractionsRoute: ApiPublicDiscordInteractionsRoute,
  ApiPublicDiscordOauthCallbackRoute: ApiPublicDiscordOauthCallbackRoute,
  ApiPublicDiscordOauthStartRoute: ApiPublicDiscordOauthStartRoute,
  ApiPublicDiscordRegisterCommandsRoute: ApiPublicDiscordRegisterCommandsRoute,
  ApiPublicLicenseValidateRoute: ApiPublicLicenseValidateRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
